script/gdb: replace flags (MS_xyz -> SB_xyz)
Since commit (1751e8a6cb935e555fcdbcb9ab4f0446e322ca3e)
Rename superblock flags (MS_xyz -> SB_xyz). script/gdb
need replace MS_xyz to SB_xyz.

Fix following problem:

root@localhost:/data# gdb -q vmlinux
Reading symbols from vmlinux...done.
Traceback (most recent call last):
  File "/data/vmlinux-gdb.py", line 32, in <module>
    import linux.proc
  File "/data/scripts/gdb/linux/proc.py", line 15, in <module>
    from linux import constants
  File "/data/scripts/gdb/linux/constants.py", line 2, in <module>
    LX_SB_RDONLY = MS_RDONLY
NameError: name 'MS_RDONLY' is not defined
(gdb)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>